In [1]:
# pytorch libraries
import torch
import torch.nn as nn
import torch.nn.functional as F
import torch.optim as optim
from torch.utils.data import Dataset, DataLoader

# for visualizing the results
import numpy as np
import matplotlib.pyplot as plt

# for reading input data
import pandas as pd

# for parsing the FEN of chess positions
import re

In [18]:
class Net(nn.Module):

    def __init__(self):
        super(Net, self).__init__()
        self.fc1 = nn.Linear(64, 64)
        self.fc2 = nn.Linear(64, 1)


    def forward(self, x):
        x = torch.flatten(x, 1)
        x = F.relu(self.fc1(x))
        x = self.fc2(x)
        return x

In [6]:
net = torch.load('chess.pth')

In [7]:
print(net)

OrderedDict([('fc1.weight', tensor([[ 0.1800,  0.1758,  0.2018,  ...,  0.2444,  0.3693,  0.3016],
        [-0.4796, -0.3306, -0.3421,  ..., -0.0760,  0.1855,  0.1712],
        [-0.2249, -0.1983, -0.2184,  ..., -0.5391, -0.4880, -0.4723],
        ...,
        [-0.2974, -0.1772, -0.2977,  ..., -0.6347, -0.7507, -0.6306],
        [ 0.2141,  0.3104,  0.2724,  ...,  0.2353,  0.3113,  0.2234],
        [-0.0351,  0.1895,  0.1829,  ...,  0.2006,  0.2652,  0.2868]],
       device='cuda:0')), ('fc1.bias', tensor([ 0.2981, -0.2535,  0.2771,  0.2300,  0.2028,  0.2985,  0.2444,  0.5654,
        -0.2777,  0.2984,  0.3115,  0.2199,  0.1980,  0.1995,  0.2738,  0.2300,
         0.1942,  0.1575,  0.2979,  0.2617,  0.2117,  0.1617,  0.1926,  0.2007,
         0.5081,  0.3370,  0.3412,  0.3197,  0.3914,  0.3916,  0.3435,  0.3391,
         0.3439,  0.3429,  0.2739,  0.2295,  0.3802,  0.3430,  0.3672,  0.0864,
         0.2769,  0.2971,  0.3434,  0.1902,  0.2634,  0.2990,  0.1442,  0.2593,
         0.3430,  0

In [5]:
weight_arrays = [param.data.numpy() for param in net.parameters()]
print(weight_arrays)

AttributeError: 'collections.OrderedDict' object has no attribute 'parameters'

In [9]:

net2 = torch.load('chess_tiny.pth')
print(net2)
w1 = net["fc1.weight"]
b1 = net["fc1.bias"]
w2 = net["fc2.weight"]
b2 = net["fc2.bias"]

print(w1)
print(b1)
print(w2)
print(b2)

OrderedDict([('fc1.weight', tensor([[ 0.4656,  0.1517,  0.2641,  ...,  0.2395,  0.2603,  0.2850],
        [-0.0168, -0.2749, -0.4193,  ..., -1.6439, -0.8214, -0.6334],
        [-0.1421, -0.2281, -0.3216,  ..., -0.5352, -0.8456, -0.7672],
        ...,
        [ 0.5441,  0.4483,  0.4503,  ...,  0.3109,  0.2423,  0.4873],
        [ 0.3578,  0.3782,  0.6411,  ...,  0.2848,  0.1684,  0.3276],
        [-0.0068,  0.6268,  0.4231,  ...,  0.4748,  0.2850,  0.5222]],
       device='cuda:0')), ('fc1.bias', tensor([0.2895, 0.6768, 0.7439, 0.6959, 0.1398, 0.3513, 0.3062, 0.3990, 0.2071,
        0.6685, 0.1605, 0.3162, 0.2956, 0.2609, 0.2799, 0.2091],
       device='cuda:0')), ('fc2.weight', tensor([[ 3.0580, -6.4507, -5.9178, -2.7165,  4.5061, -5.8261,  6.6025,  7.7898,
          4.6468, -4.6294,  3.8689,  6.2828,  4.8656,  4.8739,  5.4624,  2.1674]],
       device='cuda:0')), ('fc2.bias', tensor([-0.4611], device='cuda:0'))])
tensor([[ 0.1800,  0.1758,  0.2018,  ...,  0.2444,  0.3693,  0.3016],
  

In [12]:
from pprint import pprint
torch.set_printoptions(threshold=10_000)
pprint(w1)
pprint(b1)
pprint(w2)
pprint(b2)

tensor([[ 1.8001e-01,  1.7576e-01,  2.0181e-01,  2.2270e-01,  2.0574e-01,
          1.5687e-01,  2.2867e-01,  2.2823e-01,  2.1058e-01,  2.1092e-01,
          2.2266e-01,  1.8443e-01,  2.0856e-01,  1.3921e-01,  1.9142e-01,
          1.9020e-01,  1.8656e-01,  2.4432e-01,  2.5034e-01,  2.5899e-01,
          2.2930e-01,  2.3821e-01,  2.6262e-01,  2.4300e-01,  2.2965e-01,
          3.0019e-01,  2.5171e-01,  2.8659e-01,  3.1943e-01,  2.7832e-01,
          2.8410e-01,  3.0084e-01,  2.7188e-01,  2.4689e-01,  3.0336e-01,
          3.0039e-01,  2.6988e-01,  2.8692e-01,  3.1422e-01,  3.1462e-01,
          2.5214e-01,  2.7542e-01,  2.5959e-01,  2.3878e-01,  2.6179e-01,
          2.9814e-01,  2.9203e-01,  2.8750e-01,  2.5104e-01,  2.5378e-01,
          2.7796e-01,  2.6890e-01,  2.5974e-01,  2.8052e-01,  3.2240e-01,
          3.3634e-01,  2.3469e-01,  2.5459e-01,  2.4892e-01,  2.3435e-01,
          2.9404e-01,  2.4444e-01,  3.6930e-01,  3.0157e-01],
        [-4.7961e-01, -3.3063e-01, -3.4209e-01, -1

In [13]:
U, S, Vh = torch.linalg.svd(w1)

In [14]:
print(U)

tensor([[ 9.5884e-02, -2.9947e-02, -2.2759e-02,  7.3828e-03,  3.5557e-03,
         -8.0054e-03, -8.1883e-03,  4.1559e-02, -1.7696e-02,  5.1350e-03,
          2.8254e-03, -2.9427e-03, -5.9085e-03, -1.0024e-02,  7.1741e-04,
          2.6361e-03,  1.9283e-02,  2.6181e-02,  1.5541e-02, -1.2163e-03,
          2.7481e-02,  1.4923e-02, -1.2715e-02,  1.1130e-02,  2.2466e-02,
         -1.7634e-02, -1.4201e-02, -3.5441e-02,  4.2229e-02, -2.1961e-02,
          2.1422e-03, -6.0085e-02,  9.5567e-03, -2.1831e-02, -1.3752e-01,
         -8.4522e-03, -7.2989e-02,  6.1577e-02, -4.1158e-02, -7.3930e-02,
          3.9179e-02, -1.0928e-01, -8.1916e-03, -3.2982e-02, -8.6440e-03,
          1.1098e-01,  9.8519e-02, -9.0938e-02,  1.7898e-01, -1.8767e-03,
          5.0725e-02,  2.2402e-01, -2.8861e-02, -2.4298e-01, -9.4622e-02,
          4.5692e-02, -1.4578e-01, -4.3001e-01,  2.2809e-01,  6.2072e-01,
          1.9781e-01, -3.4297e-02, -1.5582e-01,  1.7789e-01],
        [ 7.1963e-02,  2.2837e-01, -3.8313e-01, -4

In [ ]:
w1 = net["fc1.weight"]
b1 = net["fc1.bias"]
w2 = net["fc2.weight"]
b2 = net["fc2.bias"]
w3 = net["fc3.weight"]
b3 = net["fc3.bias"]

In [19]:
import numpy as np
csv = np.genfromtxt ('weightsFC1.txt', delimiter=",")
csv2 = np.genfromtxt ('weightsFC2.txt', delimiter=",")
net2 = Net()

In [20]:
net2.fc1.weight.data = torch.tensor(csv)
net2.fc2.weight.data = torch.tensor(csv2)

In [21]:
net2

Net(
  (fc1): Linear(in_features=64, out_features=64, bias=True)
  (fc2): Linear(in_features=64, out_features=1, bias=True)
)